Improve runtime
wfondrie/mokapot pull request #44
Opened 2022-03-02 15:04 UTC by sambenfredj

- Expose max workers parameter to cli
- update triqler package with the fix for  [issue #13](https://github.com/statisticalbiotechnology/triqler/issues/13) (calculating PEPs may be extremely slow  for some runs)
- make grid search run with multi-threading

![image](https://user-images.githubusercontent.com/100685091/156387119-c07f41aa-a156-4d35-a0e1-2570a784df67.png)

2022-03-02 20:10 UTC, wfondrie requested changes
Hi @sambenfredj - thanks for the great PR! 🎉 

It looks like the code currently fails our lint tests. One way to fix this is to use [Black](https://black.readthedocs.io/en/stable/) as a pre-commit hook. To do this, first install pre-commit:
```
# With pip:
pip install pre-commit

# With conda:
conda install -c conda-forge pre-commit 
```

Once you have pre-commit installed, you can set up the hook with:
```
pre-commit install
```
Now black will run automatically with each new commit.

Lastly, we should add a test that incorporates the new `max_workers` CLI argument. I think it may be too difficult to test whether the argument is truly working, so my suggestion is merely to add it to our basic CLI system test here:
https://github.com/wfondrie/mokapot/blob/bed4946e94690c6fe8ca13299b58a5cfb7eda285/tests/system_tests/test_cli.py#L45-L72

Please don't hesitate to reach out if you have any questions!

2022-03-02 20:10 UTC, wfondrie commented on mokapot/config.py
> +        help="The number of processes to use for model training."
This line needs a trailing comma to pass our lint tests.

2022-03-02 20:10 UTC, wfondrie commented on setup.cfg
> +    triqler @ git+ssh://git@github.com/statisticalbiotechnology/triqler.git
I don't like having a non-PyPI dependency here, although it seems to make a large difference. I'll look into why this update isn't on PyPI yet.

2022-03-03 18:38 UTC, wfondrie commented
It looks like tests are failing currently, because our GitHub Actions workflows are not setup to clone repos with ssh; hence, it fails to install mokapot with the changed Triqler depedency. 

I've reached out the Triqler folks to get an ETA on when the recent patch will be in a release. If it is relatively soon, we should revert the dependency change in `setup.cfg` and instead bump the minimum version to the new release once it is live.

2022-03-03 21:11 UTC, gessulat commented
That totally makes sense. We heard that @MatthewThe is on vacation currently and were just excited to get this out as quickly as possible ;)
Thank you for the super quick response!

2022-03-04 14:18 UTC, MatthewThe commented
I updated Triqler on PyPI (v0.6.2), let me know if you run into any other issues.

2022-03-04 16:49 UTC, wfondrie commented
Thanks @MatthewThe!

@sambenfredj and @gessulat - if you change the triqler dependency to  `triqler>=0.6.2`, the test should be able to run. Once we confirm all of the tests are passing, it'll be ready to merge.

2022-03-07 09:45 UTC, sambenfredj commented
Thanks @wfondrie ! I just updated the triqler to the latest release.

2022-03-09 08:29 UTC, tkschmidt commented
Hey @wfondrie,
I'm taking over for @sambenfredj  as she is on vacation. I'm not really firm with the test pipelines in github. Can we trigger it again just to see if it resolves it. As far as I know it worked on our local systems (bad excuse ;))

2022-03-09 17:21 UTC, wfondrie commented
I'm a bit stumped as to why the Ubuntu test hangs for hours. I'll try kicking it off again and see if it completes this time. 

Either way, I'll merge this into master. However, I'm going to hold off creating a new release if it doesn't work, so that I can troubleshoot it a little more.

2022-03-09 23:58 UTC, merged

2022-03-11 23:34 UTC, wfondrie commented
mokapot v0.8.0 is now on PyPI 🎉 

It should be up on bioconda as well within the next few days.

2022-05-02 18:50 UTC, wfondrie commented
Hi @sambenfredj, @tkschmidt, and @gessulat - I'm planning to tweet about recent updates to things soon and I wanted to mention your contribution here. I can mention you each individually (@sambenfredj - do you have a twitter handle?), MSAID, or both - whatever your preference 😄. 

It's also fine if you don't want to be mentioned - please just let me know.

2022-05-03 07:55 UTC, sambenfredj commented
Thank you @wfondrie, I am glad to be mentioned. You can find me under the twitter handle **SamiaFredj**.

2022-05-03 09:51 UTC, gessulat commented
Hi @wfondrie,
thank you so much, I would be happy about being mentioned but it was really all @sambenfredj who did the all the work. So if it's to much names for a tweet just leave me out ;)